// Generated by scripts/gen-contracts.sh from packages/contracts/python/hq_contracts/models.py.
// Never edit by hand: change the Python models, then run `make contracts`.
// Contracts are frozen (docs/03); a change needs a reviewed PR and a SCHEMA_VERSION bump.

export const SCHEMA_VERSION = "1.0" as const;

/**
 * This interface was referenced by `Bundle`'s JSON-Schema
 * via the `definition` "Tier".
 */
export type Tier = "A" | "B" | "C";
/**
 * This interface was referenced by `Bundle`'s JSON-Schema
 * via the `definition` "DataMode".
 */
export type DataMode = "mock" | "showcase" | "live" | "snapshot";
/**
 * This interface was referenced by `Bundle`'s JSON-Schema
 * via the `definition` "Phase".
 */
export type Phase = "P" | "S";

/**
 * Hidden Quakes contracts, schemaVersion 1.0
 */
export interface Bundle {
  catalog: CatalogEvent[];
  confidence: Confidence;
  events: SeismicEvent[];
  evidence: EventEvidence;
  features: GeoFeature[];
  live: LiveStatus;
  meta: BundleMeta;
  stations: Station[];
  validation: Validation;
}
/**
 * This interface was referenced by `Bundle`'s JSON-Schema
 * via the `definition` "CatalogEvent".
 */
export interface CatalogEvent {
  depthDatum: string;
  depthKm: number;
  elevM: number;
  enu: Enu;
  id: string;
  latitude: number;
  longitude: number;
  mag: number | null;
  magType: string | null;
  matchedEventId: string | null;
  source: string;
  t: number;
}
/**
 * Position relative to the run origin, in meters.
 *
 * This interface was referenced by `Bundle`'s JSON-Schema
 * via the `definition` "Enu".
 */
export interface Enu {
  e: number;
  n: number;
  u: number;
}
/**
 * ML-01 (H2): one score per candidate event from a classifier trained to tell recovered
 * public events from the rest, with the model's metadata and its held-out ROC AUC. A sidecar
 * of the run (``confidence.json``) and an optional bundle file next to ``validation.json``;
 * absent means no score and no card row. Added Sat evening after the contract freeze as a new
 * file that carries its own ``schema`` tag, so ``SCHEMA_VERSION`` and every frozen bundle stay
 * as they are. ``scores`` are not probabilities that an event is real (docs/00).
 *
 * This interface was referenced by `Bundle`'s JSON-Schema
 * via the `definition` "Confidence".
 */
export interface Confidence {
  heldOutRocAuc: number | null;
  model: {
    [k: string]: unknown;
  };
  runId: string;
  schema: "hq.confidence/1";
  scores: {
    [k: string]: number;
  };
}
/**
 * This interface was referenced by `Bundle`'s JSON-Schema
 * via the `definition` "SeismicEvent".
 */
export interface SeismicEvent {
  catalogMatch: CatalogMatch | null;
  depthKm: number;
  elevM: number;
  enu: Enu;
  id: string;
  latitude: number;
  longitude: number;
  magnitude: Magnitude | null;
  meanPickProb: number;
  pickIds: string[];
  quality: LocationQuality;
  revealOrder: number;
  runId: string;
  source: string;
  t: number;
  tier: Tier;
  tierReasons: string[];
}
/**
 * This interface was referenced by `Bundle`'s JSON-Schema
 * via the `definition` "CatalogMatch".
 */
export interface CatalogMatch {
  catalogId: string;
  distM: number;
  dtS: number;
}
/**
 * This interface was referenced by `Bundle`'s JSON-Schema
 * via the `definition` "Magnitude".
 */
export interface Magnitude {
  sigma: number | null;
  type: string;
  value: number;
}
/**
 * This interface was referenced by `Bundle`'s JSON-Schema
 * via the `definition` "LocationQuality".
 */
export interface LocationQuality {
  depthOnEdge: boolean;
  gapDeg: number;
  hErrM: number | null;
  method: "pyocto" | "grid1d" | "grid3d" | "relative";
  minEpiDistM: number;
  nP: number;
  nS: number;
  nStations: number;
  rmsS: number;
  statics: boolean;
  vErrM: number | null;
}
/**
 * This interface was referenced by `Bundle`'s JSON-Schema
 * via the `definition` "EventEvidence".
 */
export interface EventEvidence {
  eventId: string;
  /**
   * @minItems 2
   * @maxItems 2
   */
  filterHz: [number, number];
  traces: WaveformSnippet[];
}
/**
 * This interface was referenced by `Bundle`'s JSON-Schema
 * via the `definition` "WaveformSnippet".
 */
export interface WaveformSnippet {
  channel: string;
  dt: number;
  epiDistM: number;
  pickP: number | null;
  pickS: number | null;
  predP: number | null;
  predS: number | null;
  probP: number | null;
  probS: number | null;
  samples: number[];
  stationId: string;
  t0: number;
}
/**
 * This interface was referenced by `Bundle`'s JSON-Schema
 * via the `definition` "GeoFeature".
 */
export interface GeoFeature {
  id: string;
  kind: "well" | "facility" | "boundary";
  name: string;
  path: Enu[];
  source: SourceRef;
}
/**
 * This interface was referenced by `Bundle`'s JSON-Schema
 * via the `definition` "SourceRef".
 */
export interface SourceRef {
  citation: string;
  url: string;
  verified: boolean;
}
/**
 * This interface was referenced by `Bundle`'s JSON-Schema
 * via the `definition` "LiveStatus".
 */
export interface LiveStatus {
  events: SeismicEvent[];
  latencyS: number;
  stationsOnline: number;
  updatedAt: number;
  windowS: number;
}
/**
 * This interface was referenced by `Bundle`'s JSON-Schema
 * via the `definition` "BundleMeta".
 */
export interface BundleMeta {
  mode: DataMode;
  run: ProcessingRun;
  scene: SceneMeta;
  schemaVersion: string;
  summary: AnalysisSummary;
}
/**
 * This interface was referenced by `Bundle`'s JSON-Schema
 * via the `definition` "ProcessingRun".
 */
export interface ProcessingRun {
  associator: {
    [k: string]: unknown;
  };
  /**
   * @minItems 4
   * @maxItems 4
   */
  bbox: [number, number, number, number];
  createdAt: string;
  gitSha: string;
  id: string;
  isSynthetic: boolean;
  locator: {
    [k: string]: unknown;
  };
  matching: {
    [k: string]: unknown;
  };
  mode: DataMode;
  picker: {
    [k: string]: unknown;
  };
  pickerModel: string;
  pickerWeights: string;
  runtimeS: {
    [k: string]: number;
  };
  softwareVersions: {
    [k: string]: string;
  };
  stationIds: string[];
  tiering: {
    [k: string]: unknown;
  };
  velocityModel: {
    [k: string]: unknown;
  };
  windowEnd: number;
  windowLabel: string;
  windowStart: number;
}
/**
 * This interface was referenced by `Bundle`'s JSON-Schema
 * via the `definition` "SceneMeta".
 */
export interface SceneMeta {
  depthLabel: string;
  heroEventId: string | null;
  isSynthetic: boolean;
  originElevM: number;
  originLat: number;
  originLon: number;
  projection: string;
  refSurfaceElevM: number;
  runId: string;
  verticalExaggeration: number;
}
/**
 * This interface was referenced by `Bundle`'s JSON-Schema
 * via the `definition` "AnalysisSummary".
 */
export interface AnalysisSummary {
  additional: TierCounts;
  additionalCount: number;
  baseline: BaselineGain | null;
  candidateCount: number;
  medianRmsS: number;
  medianStations: number;
  publicCatalogCount: number;
  recall: number;
  recoveredCatalogCount: number;
  runId: string;
  strictAdditionalCount: number;
  strictQualityCount: number;
  unmatchedPublicIds: string[];
}
/**
 * This interface was referenced by `Bundle`'s JSON-Schema
 * via the `definition` "TierCounts".
 */
export interface TierCounts {
  A: number;
  B: number;
  C: number;
}
/**
 * This interface was referenced by `Bundle`'s JSON-Schema
 * via the `definition` "BaselineGain".
 */
export interface BaselineGain {
  associationProfile: "full" | "p_only";
  gain: number;
  strictPhasenet: number;
  strictStalta: number;
}
/**
 * This interface was referenced by `Bundle`'s JSON-Schema
 * via the `definition` "Station".
 */
export interface Station {
  channels: string[];
  enu: Enu;
  id: string;
  kind: "surface" | "borehole" | "strong_motion";
  latitude: number;
  location: string;
  longitude: number;
  network: string;
  preprocessProfile: string;
  sampleRateHz: number;
  sensorDepthM: number;
  sensorElevM: number;
  staticsS: {
    [k: string]: number;
  };
  station: string;
  surfaceElevM: number;
  usedInRun: boolean;
}
/**
 * This interface was referenced by `Bundle`'s JSON-Schema
 * via the `definition` "Validation".
 */
export interface Validation {
  baseline: BaselineRow[];
  gr: GRCurve | null;
  magnitude: MagCalibration | null;
  nullTest: NullTest | null;
  sweep: SweepPoint[];
  synthetic: SyntheticTest;
}
/**
 * This interface was referenced by `Bundle`'s JSON-Schema
 * via the `definition` "BaselineRow".
 */
export interface BaselineRow {
  associationProfile: "full" | "p_only";
  candidates: number;
  medianRmsS: number;
  medianStations: number;
  method: "phasenet" | "stalta";
  recoveredPublic: number;
  tiers: TierCounts;
}
/**
 * This interface was referenced by `Bundle`'s JSON-Schema
 * via the `definition` "GRCurve".
 */
export interface GRCurve {
  bSigma: number | null;
  bValue: number | null;
  magBins: number[];
  mcPublic: number | null;
  mcRecovered: number | null;
  publicCum: number[];
  recoveredCum: number[];
}
/**
 * This interface was referenced by `Bundle`'s JSON-Schema
 * via the `definition` "MagCalibration".
 */
export interface MagCalibration {
  coefficients: {
    [k: string]: number;
  };
  looMae: number;
  n: number;
}
/**
 * This interface was referenced by `Bundle`'s JSON-Schema
 * via the `definition` "NullTest".
 */
export interface NullTest {
  meanChanceEvents: number;
  meanChanceStrict: number;
  nShuffles: number;
  shiftRangeS: number;
  stdChanceEvents: number;
}
/**
 * This interface was referenced by `Bundle`'s JSON-Schema
 * via the `definition` "SweepPoint".
 */
export interface SweepPoint {
  candidates: number;
  params: {
    [k: string]: unknown;
  };
  recoveredPublic: number;
  tierA: number;
}
/**
 * This interface was referenced by `Bundle`'s JSON-Schema
 * via the `definition` "SyntheticTest".
 */
export interface SyntheticTest {
  medianDepthBiasM: number;
  medianHErrM: number;
  medianVErrM: number;
  nEvents: number;
  p90VErrM: number;
  pickSigmaS: {
    [k: string]: number;
  };
}
/**
 * This interface was referenced by `Bundle`'s JSON-Schema
 * via the `definition` "Pick".
 */
export interface Pick {
  eventId: string | null;
  id: string;
  phase: Phase;
  picker: string;
  prob: number;
  residualS: number | null;
  stationId: string;
  t: number;
  weight: number | null;
}
