"use client";

import { useBundle, useMode } from "@/providers";
import { useDemo } from "@/state/demo";
import { Counters } from "./Counters";
import { FilterPills, ModePills } from "./Pills";
import { RevealButton } from "./RevealButton";
import styles from "./Shell.module.css";
import { useKeyboard } from "./useKeyboard";

/**
 * The overlay on top of the scene (docs/01 → Web app). Pointer-transparent, so the canvas keeps
 * orbit and drag; only the controls accept input. Every word here is a label; every number comes
 * from the provider's `AnalysisSummary` through `<Counters/>`.
 */
export function Shell() {
  const bundle = useBundle();
  // The mode is known from `?mode=` before the bundle is; the loading line names it.
  const mode = useMode();
  const phase = useDemo((s) => s.phase);
  const ready = bundle.status === "ready";
  useKeyboard({ heroEventId: ready ? bundle.meta.scene.heroEventId : null, ready });

  const synthetic = ready && bundle.info.isSynthetic;

  return (
    <div className={styles.shell} data-banner={synthetic || undefined}>
      {synthetic && <SyntheticBanner />}

      <header className={styles.header}>
        <h1 className={styles.title}>Hidden Quakes</h1>
        <p className={styles.modeLabel} data-testid="mode-label">
          {bundle.status === "ready" && bundle.info.label}
          {bundle.status === "loading" && (mode ? `Loading ${mode}…` : "Loading…")}
          {bundle.status === "error" && mode}
        </p>
      </header>

      <div className={styles.topRight}>
        {ready && <Counters summary={bundle.meta.summary} />}
        {ready && phase !== "public" && <FilterPills />}
      </div>

      {ready && phase === "public" && <RevealButton />}
      {bundle.status === "error" && <ErrorPanel message={bundle.message} />}

      <ModePills current={ready ? bundle.info.mode : null} />
    </div>
  );
}

/** Mock data on screen is never mistaken for a catalog: full-width, alert red, words only. */
function SyntheticBanner() {
  return (
    <div className={styles.banner} role="status">
      Synthetic data · generated by the mock fixture · not a catalog
    </div>
  );
}

/** The provider's own message (a schemaVersion mismatch, a missing file, a disabled mode). */
function ErrorPanel({ message }: { message: string }) {
  return (
    <div className={styles.error} role="alert">
      <p className={styles.errorTitle}>Data unavailable</p>
      <p className={styles.errorMessage}>{message}</p>
    </div>
  );
}
