"use client";

import { useMemo, useState } from "react";
import { useBundle, useMode } from "@/providers";
import { useDemo } from "@/state/demo";
import { Counters } from "./Counters";
import { DownloadButton } from "./download/DownloadButton";
import { FilterPills, ModePills } from "./Pills";
import { RevealButton } from "./RevealButton";
import { RunDetailsButton, RunDetailsPanel, useRunDetailsKey } from "./run-details/RunDetailsPanel";
import { useShareLink } from "./share";
import styles from "./Shell.module.css";
import { useKeyboard } from "./useKeyboard";
import { ValidationPanel } from "./validation/ValidationPanel";

/**
 * The overlay on top of the scene (docs/01 → Web app). Pointer-transparent, so the canvas keeps
 * orbit and drag; only the controls accept input. Every word here is a label; every number comes
 * from the provider's `AnalysisSummary` through `<Counters/>`.
 */
export function Shell() {
  const bundle = useBundle();
  // The mode is known from `?mode=` before the bundle is; the loading line names it.
  const mode = useMode();
  const phase = useDemo((s) => s.phase);
  const ready = bundle.status === "ready";
  useKeyboard({ heroEventId: ready ? bundle.meta.scene.heroEventId : null, ready });
  // DEMO-02: the Run details overlay, toggled by its button under the mode label or by D.
  const [detailsOpen, setDetailsOpen] = useState(false);
  useRunDetailsKey(setDetailsOpen, ready);
  // Share links: `?event=<id>` opens that drawer after the reveal; the address bar follows selection.
  const events = ready ? bundle.events : null;
  const eventIds = useMemo(() => (events ? new Set(events.map((e) => e.id)) : null), [events]);
  useShareLink(eventIds);

  const synthetic = ready && bundle.info.isSynthetic;

  return (
    <div className={styles.shell} data-banner={synthetic || undefined}>
      {synthetic && <SyntheticBanner />}

      <header className={styles.header}>
        <h1 className={styles.title}>Hidden Quakes</h1>
        <p className={styles.modeLabel} data-testid="mode-label">
          {bundle.status === "ready" && bundle.info.label}
          {bundle.status === "loading" && (mode ? `Loading ${mode}…` : "Loading…")}
          {bundle.status === "error" && mode}
        </p>
        {ready && <RunDetailsButton open={detailsOpen} onToggle={() => setDetailsOpen((open) => !open)} />}
        <DownloadButton />
      </header>

      <div className={styles.topRight}>
        {ready && <Counters summary={bundle.meta.summary} />}
        {ready && phase !== "public" && <FilterPills />}
      </div>

      {ready && phase === "public" && <RevealButton />}
      {bundle.status === "error" && <ErrorPanel message={bundle.message} />}

      {/* DEMO-02 panels: validation (bottom-left, after the reveal) and the Run details overlay. */}
      <ValidationPanel />
      {ready && <RunDetailsPanel open={detailsOpen} onClose={() => setDetailsOpen(false)} />}

      {/* The pressed pill is the mode chosen in the URL: during live failover the bundle says
          "snapshot" while LIVE is still what the visitor picked, and the label carries the rest. */}
      <ModePills current={ready ? (mode ?? bundle.info.mode) : null} />
    </div>
  );
}

/** Mock data on screen is never mistaken for a catalog: full-width, alert red, words only. */
function SyntheticBanner() {
  return (
    <div className={styles.banner} role="status">
      Synthetic data · generated by the mock fixture · not a catalog
    </div>
  );
}

/** The provider's own message (a schemaVersion mismatch, a missing file, a disabled mode). */
function ErrorPanel({ message }: { message: string }) {
  return (
    <div className={styles.error} role="alert">
      <p className={styles.errorTitle}>Data unavailable</p>
      <p className={styles.errorMessage}>{message}</p>
    </div>
  );
}
