"""How a window becomes a run directory: the ``PipelineRunner`` protocol and the real runner.

The worker never imports a lane's stage. ``HqPipelineRunner`` drives the pipeline through
``hq.runs``: it writes a per-window config directory (the showcase YAMLs with ``run.yaml``'s
window replaced by the live window), calls ``create_run(mode="live")`` and ``run_stages`` with
the stages from ``config.yaml``, and hands back where the run landed plus H1's waveform reader
for the exporter. A stage that is not merged yet fails inside ``run_stages`` with the owner's
name (``hq.runs.StageMissingError``); the worker records that as the window's failure.

Tests inject a fake runner that writes minimal run tables into a run directory instead.
"""

import logging
import shutil
from collections.abc import Sequence
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any, Protocol

import yaml

from hq import runs
from hq.config import RunConfig
from hq.export import WaveformSource, real_waveform_source

log = logging.getLogger(__name__)

RUN_YAML = "run.yaml"
LIVE_MODE = "live"
WINDOW_NAME_PREFIX = "live"


@dataclass(frozen=True)
class LiveWindow:
    """One data window, epoch seconds UTC; ``end`` is the data end latency is measured from."""

    start: float
    end: float

    @property
    def length_s(self) -> float:
        return self.end - self.start

    @property
    def label(self) -> str:
        return f"{iso_utc(self.start)}/{iso_utc(self.end)}"


@dataclass(frozen=True)
class PipelineRun:
    """What a runner hands back: where the run lives and what the exporter needs from it."""

    run_id: str
    run_dir: Path
    cache_dir: Path
    config: RunConfig
    waveforms: WaveformSource
    stages_ran: tuple[str, ...]


class PipelineRunner(Protocol):
    """Runs the pipeline over one window and returns the finished run."""

    def run_window(self, window: LiveWindow) -> PipelineRun:
        """Create a ``live`` run for ``window``, run its stages, return the run. Raises on any
        failure (a missing stage names its owner)."""
        ...


def iso_utc(t: float) -> str:
    """``t`` (epoch s UTC, whole seconds) as ``YYYY-MM-DDTHH:MM:SSZ``, what run.yaml parses."""
    return (
        datetime.fromtimestamp(t, tz=UTC).replace(microsecond=0).isoformat().replace("+00:00", "Z")
    )


def window_run_section(source_yaml: dict[str, Any], window: LiveWindow) -> dict[str, Any]:
    """The showcase ``run.yaml`` mapping with the live window in place of the showcase one.

    Only ``name``, ``windowStart`` and ``windowEnd`` change: bbox, origin and reference surface
    are the region's constants (docs/01 -> Conventions) and stay H2's values.
    """
    out = dict(source_yaml)
    out["name"] = f"{WINDOW_NAME_PREFIX}-{iso_utc(window.end)}"
    out["windowStart"] = iso_utc(window.start)
    out["windowEnd"] = iso_utc(window.end)
    return out


def write_window_config(source_dir: Path, target_dir: Path, window: LiveWindow) -> Path:
    """Copy every YAML of ``source_dir`` into ``target_dir`` with ``run.yaml`` rewritten for
    ``window``. ``target_dir`` is replaced if it exists."""
    source_dir, target_dir = Path(source_dir), Path(target_dir)
    run_yaml = source_dir / RUN_YAML
    if not run_yaml.is_file():
        raise FileNotFoundError(f"{run_yaml} not found; paths.configDir must hold run.yaml")
    if target_dir.exists():
        shutil.rmtree(target_dir)
    target_dir.mkdir(parents=True)
    for path in sorted(source_dir.glob("*.yaml")):
        if path.name != RUN_YAML:
            shutil.copy(path, target_dir / path.name)
    source = yaml.safe_load(run_yaml.read_text(encoding="utf-8"))
    if not isinstance(source, dict):
        raise TypeError(f"{run_yaml}: top level must be a mapping")
    section = window_run_section(source, window)
    header = (
        f"# Generated by hq_api for the live window {window.label}; the showcase run.yaml is\n"
        f"# {run_yaml}. Do not edit: the next window rewrites it.\n"
    )
    (target_dir / RUN_YAML).write_text(
        header + yaml.safe_dump(section, sort_keys=False), encoding="utf-8"
    )
    return target_dir


@dataclass(frozen=True)
class HqPipelineRunner:
    """The real runner: ``hq.runs.create_run`` + ``run_stages`` on a per-window config."""

    config_dir: Path  # the showcase config directory (paths.configDir)
    data_dir: Path  # runs and cache root (paths.dataDir resolved)
    window_config_dir: Path  # where per-window config directories go (paths.windowConfigDir)
    stages: Sequence[str]  # window.stages

    def run_window(self, window: LiveWindow) -> PipelineRun:
        target = self.window_config_dir / f"{WINDOW_NAME_PREFIX}-{iso_utc(window.end)}"
        config_dir = write_window_config(self.config_dir, target, window)
        log.info("live window %s: config at %s", window.label, config_dir)
        ctx = runs.create_run(config_dir, self.data_dir, LIVE_MODE)
        ran = runs.run_stages(ctx, list(self.stages))
        return PipelineRun(
            run_id=ctx.run_id,
            run_dir=ctx.run_dir,
            cache_dir=ctx.cache_dir,
            config=ctx.config,
            waveforms=real_waveform_source(),  # H1's reader; a clear error names H1 if absent
            stages_ran=tuple(ran),
        )
