#!/usr/bin/env bash
# Regenerate the TS contracts from the Python source of truth (docs/02 §1).
#   Bundle.model_json_schema() -> packages/contracts/schema.json -> json-schema-to-typescript
#   -> packages/contracts/ts/src/index.ts
# Deterministic: running it twice gives no diff. `make contracts` calls this.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
schema="$root/packages/contracts/schema.json"
out="$root/packages/contracts/ts/src/index.ts"

version="$(cd "$root/services/seismic" && uv run --quiet python -m hq_contracts.schema "$schema")"

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT
(
  cd "$root"
  pnpm --silent exec json2ts \
    --input "$schema" \
    --additionalProperties=false \
    --unreachableDefinitions \
    --bannerComment "" \
    --style.printWidth=100 \
    > "$tmp"
)

{
  echo "// Generated by scripts/gen-contracts.sh from packages/contracts/python/hq_contracts/models.py."
  echo "// Never edit by hand: change the Python models, then run \`make contracts\`."
  echo "// Contracts are frozen (docs/03); a change needs a reviewed PR and a SCHEMA_VERSION bump."
  echo
  echo "export const SCHEMA_VERSION = \"$version\" as const;"
  echo
  cat "$tmp"
} > "$out"

echo "wrote $out (schemaVersion $version)"
